### ISSUE TITLE
Armstrong mission statement

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#33]
As part of the Armstrong documentation it would be good to have a mission statement to guide the inclusion and updating of new components into Armstrong. Bulletpoints below to inspire responses:
- What is the objective of Armstrong?
- What would you, in your individual role, like to get out of Armstrong?
- What is the medium to long-term future of Armstrong?
- What are the principles of upgrading Armstrong?
- When is something too project-specific for Armstrong?
- When should something be moved into Armstrong?
- When should something be taken out of Armstrong?
- What is happening with versioning of Armstrong?
- Who is responsible for what for Armstrong?

**Comment by jonnystoten** [comment]
> What is the objective of Armstrong?

In my opinion, it should be to allow us (at Rocketmakers) to be able to be more productive when working for clients. Any benefit anyone outside Rocketmakers gets is a nice bonus, but shouldn't be a core objective. Also worth mentioning that one of the main reasons for open-sourcing it was so that we don't have to go through the hassle of hosting our own private npm packages, and simplifying client hand-over (no need to license Armstrong to clients separately).

> What would you, in your individual role, like to get out of Armstrong?

1. To be able to implement something functional in the frontend without having to worry about whether it looks like absolute shit.
2. To be able to use controls like e.g. DatePicker, and know that it will work with other Rocketmakers-written code.

> What is the medium to long-term future of Armstrong?

Not sure I have a good answer, but this question made me think... It will be interesting to see what happens when we hand over a project to a client's dev team. This issue page might (for better or worse) turn into a support area for clients who've left us.

> What is happening with versioning of Armstrong?

[Semantic Versioning](http://semver.org/)

> What are the principles of upgrading Armstrong?

Tricky one. This is A Thing about code reuse -- the more reuse you have, the more you're coupled to particular versions of libraries. Once we hit v1 I would hope the frequency of releases with breaking changes drops off a lot.

**Comment by simon-rocketmaker** [comment]
> What is the objective of Armstrong?

I think there are two obvious routes to go down:

1. A lightweight foundation for every web project Rocketmakers do (agree with @jonnystoten about non-Rocketmakers users) with an emphasis on preserving backwards compatibility for reuse and improvement of other projects. Probably the lighter weight the better (maybe just core components like grid, button etc.). I think this option suits the size of our team, and the nature of multiple ongoing projects best. Downside is potentially hampering innovation for the sake of backwards compatibility.

2. Less concern for breaking changes with "old" projects that use Armstrong, but a focus on innovation and new features/components. I think my opinion now is that new features/components should live in the project, not the framework, but always use the core components mentioned in Option 1. Chances are some of those new features will use a combination of front and/or back-end technologies that might change from project to project, anyway.

> What would you, in your individual role, like to get out of Armstrong?

- To design (build?) web projects in a web medium.
- To create a consistent design/front-end process that different people can dip in and out of without a learning curve.
- To design more quickly and encourage cross-discipline involvement and iteration from day 1.
- To reduce design wastage by contributing to production front-end.
- To create good quality responsive front-end code quickly and easily.
- The ability to reuse UI across web projects.
- To produce automatic style guides for customers and their dev teams.

> Semantic Versioning

@jonnystoten Sounds from that article that Armstrong could qualify as v1.y.z? (Used in production environment, worrying about backwards compatibility) Although there are rapid changes it feels like they are improvements to the basic functionality rather than breaking changes.

> Who is responsible for what for Armstrong?

@adamiprinciples has done everything on Armstrong so far and the results are fantastic but the pressure and responsibility is all on one guy. If it's to be the foundation for every Rocketmakers web project then I think it's worth making sure that's sustainable.

**Comment by richardgodfrey** [comment]
•	What is the objective of Armstrong?
Fast prototyping; allow developers to make something that look ok; provide consistent baseline controls; allow designs/prototypes to migrate easily to real products. 
•	What would you, in your individual role, like to get out of Armstrong?
Reduce risk of development through fast, iterative, active (rather than static) designs; increase profitability of some jobs through Armstrong component re-use; 
•	What is the medium to long-term future of Armstrong?
After all Adam’s hard work and input from Simon/Phil/Joe, I hope it is the focus for all our front-end design and development core controls for the foreseeable future (while using react at least!). 
•	What are the principles of upgrading Armstrong?
I don’t know – it feels as though Armstrong should focus on the core components used in practically all projects. I think those will stabilize pretty quickly and hopefully avoid significant backwards compatibility issues. 
•	When is something too project-specific for Armstrong?
When a control is not used in > 2 projects?
•	When should something be moved into Armstrong?
After the initial set of core controls… in the 3rd or 4th project it’s needed in?  Or perhaps we should just broadly copy Bootstrap?
•	When should something be taken out of Armstrong?
Errr… never? But I realise I shouldn’t say that!  Deprication of features could be done but needs to be heavily documented and we’d need to closely track usage of components in projects.
•	What is happening with versioning of Armstrong?
Yep, Semantic for sure.
•	Who is responsible for what for Armstrong?
Adam does the work – I take the glory again? ;-)   Seriously, it is important to spread the load more but I don’t know who should do what.

**Comment by philrocketmaker** [comment]
> What is the objective of Armstrong?

To establish a **core/minimal** set of layout tools and wrapper to help us build the more boring/repetitive aspects of app development quicker and more consistently.

> What would you, in your individual role, like to get out of Armstrong?

It should be a time saving utility. It should never be a substitute for design, and shouldn't lead the design process. We should never limit ourselves in the design of a product to what's already in Armstrong, just because it's convenient.

> What is the medium to long-term future of Armstrong?

I'd like to see several off-shoots from Armstrong, some high-level componentry that's based on the Armstrong core, like:

- Blogging elements
- Social networking elements
- Registration/login
- Graphs/charts

Again, these should be viewed as a boilerplate to be built on and modified per-project, rather than something we can just throw out the door with an API behind it.

> What are the principles of upgrading Armstrong?

I would hope that once things have settled, upgrades should seldom happen.

I think it's a dangerous assumption to think that we'll simply be able to upgrade Armstrong on previous projects in order to fix bugs. I'd hope that Armstrong will be viewed as a first-cut, and would be customised on a per-project basis (obviously grid is unlikely to need any customisation).

If we're avoiding customising stuff just because we're worried about breaking upgradability, we've gone wrong.

> What is happening with versioning of Armstrong?

Should it matter? Again, I'm hoping that once this is stabilised, it should just be a case of taking whatever is latest and using it. I'd be very nervous about upgrading Armstrong once per-project customisations have been made.

> Who is responsible for what for Armstrong?

Obviously the load needs to be shared more, some thought needs to be given to how we maintain consistency (React prop names/types, markup, CSS naming conventions) and avoid duplication wherever possible.

If React Native is something we plan on doing again (which it should be!) I'd happily volunteer to port Armstrong over into native land.

**Comment by jonnystoten** [comment]
> If React Native is something we plan on doing again (which it should be!) I'd happily volunteer to port Armstrong over into native land.

What is involved in this? Not to derail this too much, just curious ;)

**Comment by philrocketmaker** [comment]
> > If React Native is something we plan on doing again (which it should be!) I'd happily volunteer to port Armstrong over into native land.

> What is involved in this? Not to derail this too much, just curious ;)

React Native's layout system mimics CSS flexbox, so it _should_ just be a case of taking what's been written in CSS and HTML markup and converting it to native views and javascript-based styling rather than CSS.

While not everything would be the same, it would make React Native much more familiar to those who have yet to have the pleasure of working with it.

**Comment by jlews** [comment]
**What is the objective of Armstrong?**

To provide front-end developers with a consistent starting point for structuring user interfaces, and to allow faster app prototype building.

**What would you, in your individual role, like to get out of Armstrong?**

A framework that provides the very basic elements of UI structure to avoid base level repetition without compromising creativity or flexibility.

**What is the medium to long-term future of Armstrong?**

I think that's probably a question that needs to be answered by committee, I think it depends on everyone's expectations.

**What are the principles of upgrading Armstrong?**

At this stage I think it's hard to avoid breaking changes as we're still feeling out which components we want / don't want. I'm thinking we should keep a future V1 as minimal as possible to avoid removal of components that people are already using. Adding components/props in the future is far less likely to cause a problem than removing them.

**When is something too project-specific for Armstrong?**

If Armstrong is simple / flexible enough, then never... ideally...

**When should something be moved into Armstrong?**

When we realise that we're copying the same small, simple piece of html/css into several apps without much tweaking, or at least without tweaking that couldn't be passed in as a prop.

**When should something be taken out of Armstrong?**

Post V1? Never. Now? If we all decide it's not useful.

**What is happening with versioning of Armstrong?**

It's a bit crazy at the moment which is fair enough as the basics are still being built. In truth we probably started using it before it was ready. In the future I'm guessing we should do non-breaking bug fixes as minor versions, and documented breaking changes as major versions.

**Who is responsible for what for Armstrong?**

That's a tough one, I think we need to decide the best approach to that as a group.

**Comment by DannyWilliamson** [comment]
> What would you, in your individual role, like to get out of Armstrong?

I'd like to use Armstrong to help implement the frontend at a basic functioning level easily and efficiently that looks half decent. Where I can quickly test the repercussions of my code on the UI. To get the UI to a reliable state for handover to someone with better css skillz

**Comment by WebWalks** [comment]
- What is the objective of Armstrong?
To enable anyone to create a simple UI thats not awful, and provide a well understood presentation core across all projects
 
- What would you, in your individual role, like to get out of Armstrong?
The ability to quickly build a UI project (via a skeleton), and use simple consistent React controls to create a UI that a skilled front-end dev can improve upon (doesn't need to completely throw it away!!)

- What is the medium to long-term future of Armstrong?
Its difficult to tell long-term with the progression of IT, the next generation of browser technology could easily completely change our approach to many of the concepts/ideas.
I think keep Armstrong to just the basics

- What are the principles of upgrading Armstrong?
Semver - using semantic versioning gives a clear indication of whether (or not) the project can upgrade to the new version

- When is something too project-specific for Armstrong?
I think Armstrong should just contain the core elements, basically a reflection of the HTML spec
Any additional controls should be developed externally of Armstrong and packaged into their own distribution packages (npm etc). We should aim to make these controls NOT dependent on Armstrong as much as we possibly can

- When should something be moved into Armstrong?
If the HTML spec is extended, or we find a core UI practice being repeated over and over and should be encapsulated into this framework

- When should something be taken out of Armstrong?
If the HTML spec is deprecated, hopefully we never need to remove items (as they should only go in if they are bonafide useful)

- What is happening with versioning of Armstrong?
Use Semver - we need to put a 'stake in the ground' at some point and create a v1 to being the semver process proper (until v1 we can do whatever we like)!

- Who is responsible for what for Armstrong?
I think the front-end guys should collaborate on appropriate changes (keeping in mind whether or not you are breaking backward compatibility) - any contentious decisions should be opened to everyone.

**Comment by adamiprinciples** [comment]
**What is the objective of Armstrong?**
Two-fold really. Firstly reducing boilerplate UI code when starting a new react based project and secondly allowing the creation of projects where any developer, front or back, has an understanding of how the ui is constructed.

**What would you, in your individual role, like to get out of Armstrong?**
As above. I'd also like people to feel comfortable making contributions. I'd rather not be endlessly fixing issues when everyone here is probably more than capable of helping out ;)

**What is the medium to long-term future of Armstrong?**
Optimise and improve existing components. Try to stabilise for 1.0.

**What are the principles of upgrading Armstrong?**
Pre 1.0, anything within reason goes. Breaking changes will happen, but users should be informed when they are made if possible.

**When is something too project-specific for Armstrong?**
When it is only used once, or is domain specific. An example would be an 'itinerary card' component in travel local. This would most likely never be used outside. If it was, it should be refactored to be domain agnostic.

**When should something be moved into Armstrong?**
When it is used multiple times and isn't a domain specific thing, as clarified by the above.

**When should something be taken out of Armstrong?**
When it is made obsolete by a new component, it is never used or a group consensus is reached

**What is happening with versioning of Armstrong?**
Pre 1.0, the semver stuff we've got going on now works ok. Post that, I think we should discuss nearer 1.0.

**Who is responsible for what for Armstrong?**
Anyone should feel free to do anything they are confident with. For 'controversial' or opinion based changes, use branches or pull requests. Don't do anything without telling others what you're doing. Remember it's used in a fair few projects now.

**Comment by simon-rocketmaker** [comment]
My attempt based on the above and recent conversations/updates - feel free to throw away or iterate:

**Armstrong is:**
- Simple and lightweight - a "foundation" framework.
- An aid to produce good quality, consistent UI quickly.
- A well documented tool that both developers and designers can be comfortable using.
- Flexible enough for per-project use cases.
- For Rocketmakers and our clients.

**Armstrong is not:**
- A dumping ground for infrequently used components.
- Slower than doing it yourself.
- Legacy-constrained.
- For wider use.
- About reuse of complex UI components.

**Comment by adamiprinciples** [comment]
Archiving this off so it doesn't effect any milestones :)
