### ISSUE TITLE
What is responsiveness in Armstrong?

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#45]
Should there be a standard responsive behaviour for Armstrong? If so, what should it be?

So far I have been very happy with the responsive classes in the add-on for apps I work on (with the exception of the variables discussed in #34 ) and wouldn't want to lose those just for speculative reusability. That said I also don't expect everyone to like it, or think that everyone should have to use it so for now I vote to keep responsiveness outside.

**Comment by adamiprinciples** [comment]
I've thought about this, and I definitely think it should be a core part of armstrong for a few reasons:

1) 100% reliant on the grid. It wont work without it and any changes to grid could break it
2) Almost every site we build needs to be responsive, so we'd end up importing it every time anyway
3) It's very flexible. What you've done gives enough flexibility to handle pretty much any scenario

So that said, I'm going to add it in, albeit in a separate import eventually (which the skeletons will import by default)

**Comment by simon-rocketmaker** [comment]
Having used the responsiveness for a few months now I am happy that it is a net time-saver with no loss of quality of code or end product so would agree with @adamiprinciples. Am, however, conscious that only three of us (Simon, Adam, Joe) know about it/have used it enough to form an opinion and wary of insisting how people should work (even though you can choose not use it). 

I would be happy to take anyone else through it to a) educate b) offer the option for people to raise concerns and c) improve it. If it is that contentious I am currently very happy with it as an addon as it fits my needs very well.

* A note on the responsiveness that will come up at some point: It currently uses % values for margin-right which at first glance sounds undesirable. Our principle with Armstrong so far has been to identify a problem/opportunity, try an mvp solution, then use it on a real project and improve it based on real world use cases. I like this approach and can't say I've yet found a real use case where I wished it was padding, or that it used the spacing variables of the project. That said, people should definitely try to do that themselves as an MVP if they want, but don't really want to go down the route of spending weeks trying to think up a hypothetical wishlist for responsiveness.
