### ISSUE TITLE
Override of $fixed-site-width doesn't seem to work

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#56]
p.s. $fixed-site-width is applied by default in Armstrong to .width-wrapper.

**Comment by adamiprinciples** [comment]
@simon-rocketmaker this does work, but your imports in theme should look like this :

```
// ARMSTRONG VARIABLE OVERRIDES
@import "./shared/variables";

// FONTS
@import "fonts";

// ARMSTRONG LIBRARY IMPORT (don't move or delete!)
@import "~armstrong-react/dist/imports";
@import "~armstrong-react/dist/style";
```

The important thing there is your armstrong variables from your project must be loaded before armstrong. Heres an example of what happens when I change fixed width to 300

![image](https://cloud.githubusercontent.com/assets/1008185/17765300/e0967c2a-651c-11e6-8583-21017b8f1d2d.png)
